language: r
sudo: required
dist: bionic
Remotes: rmsharp/rmsutilityr
cache:
  - packages
  - github_packages
r:
    - release
    - oldrel
    - devel
r_packages:
    - devtools
    - covr
    - rcmdcheck
addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev
matrix:
     include:
         - os: osx
           fortran: false
#before_install:
#  - tlmgr update --self -repository http://mirror.ctan.org/systems/texlive/tlnet/
#  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
#    - tlmgr install texlive-latex-extra -repository https://mirrors.rit.edu/CTAN/systems/texlive/tlnet/
#    - tlmgr install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended -repository http://mirror.ctan.org/systems/texlive/tlnet
#    texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
#   - Rscript -e 'install.packages("rJava", type = "source")'
script:
  - R CMD build . --no-build-vignettes --no-manual --no-resave-data
  - R CMD check *.tar.gz --as-cran --no-build-vignettes  --ignore-vignettes --no-manual
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  - global:
    - CI=TRUE
    - LINTR_COMMENT_BOT=false
